FROM glm53-exl3-tp4:keys
COPY exl3.py /usr/local/lib/python3.12/dist-packages/vllm/model_executor/layers/quantization/exl3.py
RUN rm -rf /usr/local/lib/python3.12/dist-packages/vllm/model_executor/layers/quantization/__pycache__
